# Generated by Django 5.0.2 on 2024-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalPlaylistApp', '0002_artist_festival_artists_festivalartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='artists',
        ),
        migrations.AddField(
            model_name='festival',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
