# Generated by Django 5.0.2 on 2024-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalPlaylistApp', '0003_remove_festival_artists_festival_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='festivals',
            field=models.ManyToManyField(through='festivalPlaylistApp.FestivalArtist', to='festivalPlaylistApp.festival'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
